name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk nodejs npm
          npm install -g cordova

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          mkdir -p ~/android-sdk/cmdline-tools
          unzip commandlinetools-linux-10406996_latest.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.1"

      - name: Add Android Platform to Cordova
        run: |
          cordova platform add android

      - name: Build APK
        run: |
          cordova build android --release || (echo "Cordova Build Failed!" && exit 1)

      - name: Debug APK Location
        run: |
          find platforms/android/app/build/outputs/apk/ -type f

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: platforms/android/app/build/outputs/apk/release/app-release.apk